In [ ]:
moj_dict={}
type(moj_dict)

dict

Python *strings* are "immutable" which means they cannot be changed after they are created (Java strings also use this immutable style). Like many other popular programming languages, strings in Python are arrays of bytes representing unicode characters.However, Python does not have a character data type, a single character is simply a string with a length of 1.Square brackets can be used to access elements of the string.Since strings can't be changed, we construct *new* strings as we go to represent computed values.Strings in python are surrounded by either single quotation marks, or double quotation marks. Strings are ordered: You can index and slice them and Iterable: Can loop through characters.

A *list* is a data structure in Python that is a mutable, or changeable, ordered sequence of elements. Each element or value that is inside of a list is called an item. Just as strings are defined as characters between quotes, lists are defined by having values between square brackets [ ]. Duplicates in a list a allowed. List are not hashable, can not be used as a dictionarz key.

In Python, a *tuple* is a built-in data type that allows you to create immutable sequences of values. The values or items in a tuple can be of any type and mixed.  Can be nested: ((1, 2), (3, 4)). Because tuples are immutable, they can be used as dictionary keys.
Tuples are immutable objects and lists are mutable objects. Once defined, tuples have a fixed length and lists have a dynamic length. Tuples use less memory and are faster to access than to lists. Tuple syntax uses round brackets or parenthesis, and list syntax uses square brackets.

*Sets* are a mutable collection of distinct (unique) immutable values that are unordered (No indexing or slicing).Sets are iterable: Loop through them.

In Python, a *dictionary* (or dict) is a built-in data type for storing data in key-value pairs. While keys have to be immutable (e.g., integers or strings), values can have any type, including lists or other dictionaries. Order is preserved (since Python 3.7+)

In [ ]:
#inicijalizacija s praznim, ne moze samo preko zagrada 
moj_set=set()
type(moj_set)

set

In [ ]:
#inicijalizacija s podacima, moze s viticastm zagradama
moj_set={"Ana","Marko","Mario"}
type(moj_set)

set

The most relevant commands and properties with tuples:

Accessing Elements
t[0]  # First element
t[-1] # Last element

Slicing
t[1:3]  # Returns a tuple with elements from index 1 to 2

Tuple Methods
t.count(x)   # Number of times x appears
t.index(x)   # First index of x

Unpacking Tuples
a, b, c = (1, 2, 3)
Extended unpacking: a, *b, c = (1, 2, 3, 4, 5)  # a=1, b=[2,3,4], c=5
b in this example is cast to list

Looping Through Tuples
for item in t:
    print(item)

 Membership Test
 3 in t        # True if 3 is an element of t

Tuple Concatenation and Repetition
t + (4, 5)    # (1, 2, 3, 4, 5)
t * 2         # (1, 2, 3, 1, 2, 3) -- but none change the original t

Nested Tuples
nested = ((1, 2), (3, 4), (5, 6))

Accessing elements
print(nested[0])     # (1, 2)
print(nested[0][1])  # 2

Iterating through nested tuples
for a, b in nested:
    print(f"a = {a}, b = {b}")

Looping with Unpacking
pairs = [(1, 'a'), (2, 'b'), (3, 'c')]

for number, letter in pairs:
    print(f"{number} => {letter}")

With enumerate:
words = ['alpha', 'beta', 'gamma']
for i, word in enumerate(words):
    print(f"{i}: {word}")


In [ ]:
a, *b, c = (1, 2, 3, 4, 5)
type(b)

list

In [11]:
t=(1,2,3)
t2= t + (4, 5)    # (1, 2, 3, 4, 5)
t3=t * 2         # (1, 2, 3, 1, 2, 3)
t3

(1, 2, 3, 1, 2, 3)

In [12]:
nested = ((1, 2), (3, 4), (5, 6))
for a, b in nested:
    print(f"a = {a}, b = {b}")

a = 1, b = 2
a = 3, b = 4
a = 5, b = 6


The most relevant commands and properties with list:
my_list.append(10)        # Add to end
my_list.insert(1, 99)     # Insert at index 1
my_list.extend([4, 5])    # Add multiple elements

my_list.remove("a")       # Remove first matching value
my_list.pop()             # Remove last element
my_list.pop(2)            # Remove at index 2
my_list.clear()           # Remove all items

my_list.index(3)          # Index of first occurrence
my_list.count("b")        # Count occurrences of "b"

my_list.sort()            # Sort list in place
my_list.reverse()         # Reverse list in place

#For non-destructive sorting
sorted_list = sorted(my_list)
reversed_list = list(reversed(my_list))

for item in my_list:
    print(item)

#With index
for i, item in enumerate(my_list):
    print(i, item)

#List comprehension
squares = [x**2 for x in range(5)]  # [0, 1, 4, 9, 16]

3 in my_list        # True if 3 is in the list
"x" not in my_list  # True if "x" is not

#Flatten a nested list (1 level deep)
nested = [[1, 2], [3, 4]]
flat = [item for sublist in nested for item in sublist]

#Remove duplicates (order not guaranteed)
unique = list(set(my_list))

#Deep copy, native copy() method for list is always a shallow copy
import copy

original = [[1, 2], [3, 4]]
deep = copy.deepcopy(original)

deep[0][0] = 999

print(original)  # [[1, 2], [3, 4]] ✅ Safe
print(deep)      # [[999, 2], [3, 4]]


In [37]:
#my_list=[1 for x in range(10) if x%2==0]
my_list=[1 if x%2==0 else 0 for x in range(10)]
my_list

[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]

The most relevant commands and properties with set:
s.add(4)         # Add element
s.remove(2)      # Remove element (raises error if not found)
s.discard(2)     # Remove if present (no error)
s.pop()          # Remove and return arbitrary element
s.clear()        # Empty the set

a = {1, 2, 3}
b = {3, 4, 5}


Union a.union(b)
Intersection  a & b or a.intersection(b)  {3}
Difference  a - b or a.difference(b)   {1, 2}
Symmetric Difference   a ^ b or a.symmetric_difference(b)   {1, 2, 4, 5}
Subset   a <= b or a.issubset(b)   False
Superset   a >= b or a.issuperset(b)   False
Disjoint   a.isdisjoint(b)   False
isdisjoint() method checks whether two sets have any common elements. If no common elements exist, it returns True ; otherwise, it returns False

Looping Through a Set
for item in s:
    print(item)

Membership Testing
3 in s         # True if 3 is in the set
5 not in s     # True if 5 is not in the set

Set Comprehension
squared = {x**2 for x in range(5)} # {0, 1, 4, 9, 16}

Frozen Sets (Immutable Sets)
fs = frozenset([1, 2, 3])
#fs.add(4) → ❌ will raise an error


In [15]:
a = {1, 2, 3}
b = {3, 4, 5}

a.union(b)


{1, 2, 3, 4, 5}

In [16]:
a.intersection(b)

{3}

In [18]:
b.difference(a)

{4, 5}

In [17]:
a.difference(b)

{1, 2}

In [19]:
a.symmetric_difference(b) 

{1, 2, 4, 5}

In [21]:
text = "hello hello world"
freq = {}
for word in text.split():
    freq[word] = freq.get(word, 0) + 1
type(freq)

dict

The most relevant commands and properties with dictionary:
my_dict = {"name": "Alice", "age": 25}
my_dict = dict(name="Bob", age=30)
my_dict = dict([("a", 1), ("b", 2)])

my_dict["name"]        # Get value
my_dict["age"] = 26    # Update value
my_dict["city"] = "NY" # Add key-value pair

my_dict.keys()         # dict_keys(['name', 'age', 'city'])
my_dict.values()       # dict_values(['Alice', 25, 'NY'])
my_dict.items()        # dict_items([('name', 'Alice'), ...])

my_dict.setdefault("country", "USA") #Adds key only if it doesn't exist

my_dict.update({"age": 28, "gender": "female"})  # Merge/update

my_dict.pop("age")           # Removes key & returns its value
my_dict.popitem()            # Removes and returns last (key, value)
del my_dict["city"]          # Deletes key from dict
my_dict.clear()              # Removes all items

len(my_dict)                # Number of key-value pairs
"age" in my_dict            # Membership test
list(my_dict)               # List of keys

#Keys only
for key in my_dict:
    print(key)

#Keys and values
for key, value in my_dict.items():
    print(f"{key}: {value}")

#Dictionary Comprehension
squares = {x: x**2 for x in range(5)} #{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

shallow = my_dict.copy()         # Shallow copy
import copy
deep = copy.deepcopy(my_dict)    # Deep copy (for nested dicts)

#Nesting & Complex Structures
people = {
    "alice": {"age": 25, "city": "Paris"},
    "bob": {"age": 30, "city": "NY"}
}

Task                                | Method or Function
Get value (safe)                    | dict.get(key)
Add or update key                   | dict[key] = value
Add default if missing              | setdefault()
#Interesting use of setdefault():
from collections import defaultdict  # or just use setdefault manually

data = [("fruit", "apple"), ("fruit", "banana"), ("veg", "carrot")]

grouped = {}
for category, item in data:
    grouped.setdefault(category, []).append(item)

print(grouped) # {'fruit': ['apple', 'banana'], 'veg': ['carrot']}

Loop through key–value pairs        | for k, v in dict.items()
Merge two dicts                     | dict.update()
Create from keys                    | dict.fromkeys(keys,defaultvalue) - This method creates a new dictionary with the specified keys (a list of keys) and all values set to the same default, None by defualt.
keys = ["a", "b", "c"]
my_dict = dict.fromkeys(keys)

print(my_dict)# Output: {'a': None, 'b': None, 'c': None}


In [33]:
my_dict = dict(name="Bob", age=30, surname="Dod", age_one=36)
my_dict 
my_dict.get("age")

30

In [26]:
my_dict = dict([("a", 1), ("b", 2)])
my_dict 

{'a': 1, 'b': 2}

The most relevant commands and properties with strings:
s.lower()        # 'hello'
s.upper()        # 'HELLO'
s.capitalize()   # 'Hello'
s.title()        # 'Hello World'
s.strip()        # removes leading/trailing whitespace
s.replace("l", "x")  # 'hexxo'
s.startswith("he")  # True
s.endswith("lo")    # True
s.find("l")         # 2 (first index of 'l')
s.rfind("l")        # 3 (last index of 'l')
s.count("l")        # 2
s.isalpha()      # True if only letters
s.isdigit()      # True if only digits
s.isalnum()      # True if alphanumeric
s.isspace()      # True if only whitespace
s.islower()      # True if all lowercase
s.isupper()      # True if all uppercase
"hello world".split()        # ['hello', 'world']
"one,two,three".split(",")   # ['one', 'two', 'three']
"-".join(['a', 'b', 'c'])    # 'a-b-c'
s.center(10)      # '  hello   '
s.ljust(10, '*')  # 'hello*****'
s.rjust(10, '-')  # '-----hello'


String Formatting
f-strings (Recommended in Python 3.6+)
name = "Alice"
f"Hello, {name}!"  # 'Hello, Alice!'



The most used relevant basic python functions:
len(t)       # Number of elements
min(t)       # Minimum (if elements are comparable)
max(t)       # Maximum
sum(t)       # Sum of numeric elements
enumerate() is a built-in function that adds a counter to an iterable (like a list, tuple, string, etc.) and returns it as an enumerate object, which you can loop through.
sorted(s)        # returns a sorted list of characters.can be called on a set, but still returns a sorted list
list(s)          # converts to list of characters
ord('A')         # 65 (ASCII code)
chr(65)          # 'A'


In [ ]:
#Map example
a = [1, 2, 3]
b = [4, 5, 6]

summed = list(map(lambda x, y: x + y, a, b)) #map(function, list), here function is lambda x, y: x + y and the two arguments are two list a and b
# The reason that the addition happens element ist that map work on the first element of a and a first element of b
# The return value is a1+b1, and it is that added to a list
print(summed)
# Output: [5, 7, 9]


[5, 7, 9]


In [38]:
a = [1, 2, 3]
b = [4, 5, 6]
a+b

[1, 2, 3, 4, 5, 6]

## ndarray svojstva

In [ ]:
# property size dohvaca broj elemenatata u nizu
import numpy as np
polje=np.array([1,2,3,4,5])
polje.size


5

In [44]:
polje_ndim=np.array([[1,2,3],[4,5,6], [7,8,9]])
polje_ndim.size

9

In [1]:
# Bitno za definiciju polja:
np.array([1, 2, 3]) # shape je (3,) ovo je 1D vektor s 3 elementa, nema redaka ni stupaca
np.array([[1,2,3]]) # ovdje je shape (1, 3) 1 redak   i 3 stupca, znaci 2D matrica
np.array([[1],[2],[3]]) # ovdje je shape (3, 1) 3 retka  i 1 stupac, znaci 2D matrica

NameError: name 'np' is not defined

In [48]:
# property ndim dohvaca broj dimenzija ndarray tipa. Za niz je to 1, za matricu je 2. 
# Ako bi array bio napravljen od dvije liste, a svaka lista sadrzi jos dvije liste. onda bi rezultat bio 3
print(polje.ndim)
print(polje_ndim.ndim)

polje_3dim=np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(polje_3dim.ndim)

1
2
3


In [49]:
# property shape vraca tuple koji govori koliko je ndarray velik po dimenzijama
print(polje.shape)
print(polje_ndim.shape)
print(polje_3dim.shape)

(5,)
(3, 3)
(2, 2, 2)


In [ ]:
# ndarray je namijenjen za rad s velikim kolicinama podaka
# property dtpye daje tip podatka u array
# property itemsize daje podatak koliko memorije zauzima jedan podatak u arrayu
# property nbytes daje podatak o zauzecu memorije u bytovima

print(polje_3dim.dtype)
print(polje_3dim.itemsize)
print(polje_3dim.nbytes)


int64
8
64


### ndarray metode i funkcije

In [53]:
# reshape metoda kojom se mijenja oblik odnosno shape array-a. prima tuple kao argument, ali umnozak argumenata mora biti isti kao i
# umnozak velicina dimenzija pocetnog ndarray-a

print(polje_3dim.shape) #umnozak dimenatija je 2x2x2=8
polje_3dim=polje_3dim.reshape(2,4) # ne mijenja originalni objekt, treba assignati
print(polje_3dim.shape)

(2, 2, 2)
(2, 4)


In [54]:
np.zeros((3,2,1)) # stvara ndarry dimenzije 3 samo s nulama

array([[[0.],
        [0.]],

       [[0.],
        [0.]],

       [[0.],
        [0.]]])

In [55]:
np.ones((3,2,1)) # stvara ndarry dimenzije 3 samo s jedincama

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [56]:
np.full((3,2,1), 7) # stvara ndarry dimenzije 3 samo s sedmicama, vrijednost je drugi argument!

array([[[7],
        [7]],

       [[7],
        [7]],

       [[7],
        [7]]])

In [61]:
polje_arange=np.arange(3,15,4) # stvara 1D array pocevsi od 3, s korakom 4, do vrijednosti 15, 15 nije ukljucen
print(polje_arange)
print(polje_arange.dtype)
print(polje_arange.shape)
print(polje_arange.ndim)

[ 3  7 11]
int64
(3,)
1


In [62]:
polje_linspace=np.linspace(3,15,7) # kreira 1D array s pocetkom 3, krajem na 14(ukljuceno) i daje 7 elemenata
print(polje_linspace)
print(polje_linspace.dtype)
print(polje_linspace.shape)
print(polje_linspace.ndim)

[ 3.  5.  7.  9. 11. 13. 15.]
float64
(7,)
1


In [ ]:
#ndarray slucajnih brojeva, funkciji se predaje velicine dimenzija

polje_random=np.random.randn(4,5)
print(polje_random)
print(polje_random.dtype)
print(polje_random.shape)
print(polje_random.ndim)

[[ 0.03108908 -1.53051518 -1.53978892 -1.42620969  0.58738526]
 [-0.1182661  -1.31545992 -1.35779948  0.36235298 -1.05973874]
 [-0.21131177  1.13573206 -0.33770928  0.28383753 -0.65780897]
 [-1.08476643  2.89684642  1.7463597   0.70156744 -2.17995667]]
float64
(4, 5)
2


In [117]:
# za povezivanje i razdvajanje

# Funkcija concatenate (generalizacij hstack i vstack)
niz1=np.linspace(-4,4,9)
niz2=np.random.randn(9)
print("Niz1: ", niz1)
print("Niz2: ", niz2)

# axis=0 is join along rows, axis =1 columns. In a 1D array, only axis 0 existis, concatenate elements
niz_concat=np.concatenate([niz1, niz2], axis=0) # primjeti listu
print("Konkatenirani niz: ", niz_concat)
print("Konkatenirani niz- dimenzija: ", niz_concat.shape)

# Funkcija vstack
niz_vstack=np.vstack([niz1, niz2])
print("Vstack niz: ", niz_vstack)
print("Vstack niz - dimenzija: ", niz_vstack.shape) # mijenja se dimenzija 
# Funkcija hstack
niz_hstack=np.hstack([niz1, niz2])
print("Hstack niz: ", niz_hstack)
print("Hstack niz - dimenzija: ", niz_hstack.shape)




Niz1:  [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
Niz2:  [ 0.10569467  0.29794326 -0.91120316 -0.52735975  0.23478274  1.40421368
 -0.21904326 -1.45467997  0.44939562]
Konkatenirani niz:  [-4.         -3.         -2.         -1.          0.          1.
  2.          3.          4.          0.10569467  0.29794326 -0.91120316
 -0.52735975  0.23478274  1.40421368 -0.21904326 -1.45467997  0.44939562]
Konkatenirani niz- dimenzija:  (18,)
Vstack niz:  [[-4.         -3.         -2.         -1.          0.          1.
   2.          3.          4.        ]
 [ 0.10569467  0.29794326 -0.91120316 -0.52735975  0.23478274  1.40421368
  -0.21904326 -1.45467997  0.44939562]]
Vstack niz - dimenzija:  (2, 9)
Hstack niz:  [-4.         -3.         -2.         -1.          0.          1.
  2.          3.          4.          0.10569467  0.29794326 -0.91120316
 -0.52735975  0.23478274  1.40421368 -0.21904326 -1.45467997  0.44939562]
Hstack niz - dimenzija:  (18,)


In [126]:
# Za filtriranje i sortiranje vrijednosti elemenata u nizovima koristi se where, select, unique i sort
# where
niz=np.linspace(-4,4,9)
niz_where=np.where(niz<0, niz**2, niz**3) # funkcija ne mijenja originalni niz, treba assign
print(niz_where)

# select - prima listu uvjeta i nakon nje listu operacija koje se izvrsavaju ako je uvjet zadovoljen
niz_select=np.select([niz<-1, niz<2,niz>=2], [niz**2,niz**3, niz**4]) # funkcija ne mijenja originalni niz, treba assign
print(niz_select)

# unique - izbacuje sve duplikate iz niza
niz_nonunique=np.ones((9,))
print("Nonunique: ", niz_nonunique)
niz_unique=np.unique(niz_nonunique)
print("Unique: ", niz_unique)

#sort - sortira niz
niz_random=np.random.randn(9)
niz_sortiran=np.sort(niz_random)
print("Sortiran: ", niz_sortiran)

[16.  9.  4.  1.  0.  1.  8. 27. 64.]
[ 16.   9.   4.  -1.   0.   1.  16.  81. 256.]
Nonunique:  [1. 1. 1. 1. 1. 1. 1. 1. 1.]
Unique:  [1.]
Sortiran:  [-8.85786439e-01 -6.71584887e-01 -2.60044677e-04  3.55463550e-01
  6.12887878e-01  7.49165651e-01  1.55734276e+00  1.83926301e+00
  1.84751372e+00]


__Dijeljenje i spajanje array-a__

arr.shape is (4, 4) — 4 rows and 4 columns.
<div class="alert alert-block alert-info">
arr = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12],
    [13, 14, 15, 16]
]) 
</div>

1. np.split() - Splits along a specific axis, which you must specify manually.

        1. Split into 2 parts along axis 1 (columns)
<div class="alert alert-block alert-info">
        split_arr = np.split(arr, 2, axis=1)
        </br>
        [array([[ 1,  2],
                [ 5,  6],
                [ 9, 10],
                [13, 14]]),
        array([ [ 3,  4],
                [ 7,  8],
                [11, 12],
                [15, 16]])]
</div>

This split it vertically (like hsplit), because we told it to split along columns (axis=1).

2. np.hsplit() - This is shorthand for splitting horizontally (splitting columns).
hsplit_arr = np.hsplit(arr, 2)
Same result as split(..., axis=1)!

3. np.vsplit() - This splits vertically (splitting rows).
vsplit_arr = np.vsplit(arr, 2)

<div class="alert alert-block alert-info">
        vsplit_arr = np.vsplit(arr, 2)
        </br>
        [array([[1,  2,  3,  4],
        [5,  6,  7,  8]]),
        array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]
</div>

Each part has 2 rows and 4 columns — so we split it horizontally across the middle (more rows).


__Spremanje i ucitavanje arraya__

Array se moze pospremiti u datoteku, nastane datoteka .npy i ucitati iz datotekte. Naredbe su:

- np.save('ime_datoteke', array)
- ucitani_array=np.load('ime_datoteke.npy')

__slicing array-a__

In [105]:
polje_3dim
#array([[1, 2, 3, 4],
#       [5, 6, 7, 8]])

# prvi redak
print(polje_3dim[0])
# drugi redak
print(polje_3dim[1])
# polje_3dim[2] ce vratit gresku da index-a nema, ali polje_3dim[1:7], iako dalje od 1 ni nema, ce samo ispisati redak 1
print(polje)#1D polje
#[1 2 3 4 5]
print(polje[0:3:2]) #za 1D ovo znaci idi od 0 do 3 elementa, s korakom 2, ne ukljucujuci 3ci
#za visedimenzionalne array-e
# iz retka s indexom 1, uzmi podatke iz stupaca s indexom 1 do 3, 3 nije ukljuceno s korakom 1
print(polje_3dim[1,1:3:1])

[1 2 3 4]
[5 6 7 8]
[1 2 3 4 5]
[1 3]
[6 7]


__Linerarna algebra__

1. **Vektori**
- Vektore mozemo zbrajati, oduzima i mnoziti sa skalarom
- Dulijnu vektora(aka normu) racunamo: np.linalg.norm(vektor)
2. **Matrice**
- Podrazumijeva se da ima vise od jedne dimenzije
- Matrice mozemo zbrajati, oduzima i mnoziti sa skalarom
- Matricno mnozenje je posebni nacin mnozenja prema definiciji iz linearne algebre

In [133]:
A=np.matrix([2,0,3])
print(A)
print(A.ndim)
print(A.shape)

[[2 0 3]]
2
(1, 3)


In [132]:
B=np.array([2,0,3])
print(B)
print(B.ndim)
print(B.shape)

[2 0 3]
1
(3,)


In [138]:
A=np.matrix([[2,0,3],[1,4,1]])
np.transpose(A)

matrix([[2, 1],
        [0, 4],
        [3, 1]])

In [ ]:
# definiranje objekta matrice
A=np.matrix([[2,0,3],[1,4,1]])
B=np.matrix([[1,1,1],[2,3,4]])
# Matricno mnozenje objekata matrix 
C=A*B # operator *
# Elementwise mnozenje objekata tupa matrix
C=np.multiply(A,B)
# Matricno mnozenje objekata tipa ndarray, npr. za nizove
np.array([1,2,3]) @ np.array([4,5,6,])

# Jedincna matrica
I=np.identity(5) #uvijek kvadratna, dobije se matrica velicine 5x5, ali objekt je ndarray, ne matrix

# Transponirana matrica
# Moze se kreirati pomocu funkcije ili pomocu svojsta ili metode
np.transpose(A)
A.T #svojstvo
A.transpose()

# Inverz matrice
np.linalg.inv(A)

# Za rjesavanje linearnih matricnih jednadzbi, kao primjer s pekarom, koristi se np.linalg.solve
x=np.linalg.solve(A, b.transpose())

# Pseudoinverz matrice je genralizacija inverza matrice, a koristi se za trazenje linearnog modela koji najbolje opisuje podatke
# Linerani koeficijenti pravca kojeg trazimo su k, b za  y=kx+b
# Koristi se funkcija polyfit
# x i y su nasi podaci, npr. x datumi, a y se izmjerene temperature
k, b=np.polyfit(x,y,1) 