In [1]:
import numpy as np

In [2]:
python_lista = [1, 2, 3, 4, 5]
numpy_ndarray = np.array([1, 2, 3, 4, 5])

print(f'Mnozenje Python Liste: {python_lista * 2}')
print(f'Mnozenje NumPy ndArray: {numpy_ndarray * 2}')

Mnozenje Python Liste: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Mnozenje NumPy ndArray: [ 2  4  6  8 10]


In [3]:
np.multiply(python_lista, 2)

array([ 2,  4,  6,  8, 10])

In [4]:
python_lista = [7, 9, 22] # TODO
np.multiply(python_lista, 2)

array([14, 18, 44])

In [7]:
python_lista = [] # TODO
np.multiply(python_lista, 2)

array([], dtype=float64)

In [8]:
podaci = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]],]
np_podatci = np.array(podaci)
np_podatci

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [9]:
np_podatci.size

9

In [10]:
np_podatci.ndim

3

In [11]:
lista = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], 
         [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
         [[25, 26, 27, 28], [29, 30, 31, 32] ,[33, 34, 35, 36]]]
tri_d = np.array(lista)
tri_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])

In [12]:
tri_d.ndim

3

In [13]:
np_podatci.shape

(1, 3, 3)

In [14]:
tri_d.shape

(3, 3, 4)

In [15]:
tri_d.dtype

dtype('int64')

In [16]:
tri_d = np.array(tri_d, dtype=np.float64)
tri_d

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]],

       [[25., 26., 27., 28.],
        [29., 30., 31., 32.],
        [33., 34., 35., 36.]]])

In [17]:
print('Shape tri_d:\t', tri_d.shape)
print('\nIzgled tri_d Array objekta PRIJE reshape():\n', tri_d)
# Rezultat 
# Shape tri_d:	 (3, 3, 4)

# Promjena 'oblika'
tri_d = tri_d.reshape(9, 4)
print('Shape tri_d nakon reshape():\t', tri_d.shape)
print('\nIzgled tri_d Array objekta nakon reshape():\n', tri_d)

Shape tri_d:	 (3, 3, 4)

Izgled tri_d Array objekta PRIJE reshape():
 [[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[13. 14. 15. 16.]
  [17. 18. 19. 20.]
  [21. 22. 23. 24.]]

 [[25. 26. 27. 28.]
  [29. 30. 31. 32.]
  [33. 34. 35. 36.]]]
Shape tri_d nakon reshape():	 (9, 4)

Izgled tri_d Array objekta nakon reshape():
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [17. 18. 19. 20.]
 [21. 22. 23. 24.]
 [25. 26. 27. 28.]
 [29. 30. 31. 32.]
 [33. 34. 35. 36.]]


In [18]:
# Promjena 'oblika'
tri_d = tri_d.reshape(36)
print('Shape tri_d nakon reshape():\t', tri_d.shape)
print('\nIzgled tri_d Array objekta nakon reshape():\n', tri_d)

Shape tri_d nakon reshape():	 (36,)

Izgled tri_d Array objekta nakon reshape():
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.]


In [132]:
print(tri_d.nbytes)
print(tri_d.itemsize)
print(tri_d.dtype)

288
8
float64


In [19]:
print(np_podatci.nbytes)
print(np_podatci.itemsize)
print(np_podatci.dtype)

print(tri_d.nbytes)
print(tri_d.itemsize)
print(tri_d.dtype)

72
8
int64
288
8
float64


In [20]:
lista = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], 
         [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
         [[25, 26, 27, 28], [29, 30, 31, 32] ,[33, 34, 35, 36]]]
tri_d = np.array(lista)
tri_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])

In [22]:
lista = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], 
         [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
         [[25, 26, 27, 28], [29, 30, 31, 32] ,[33, 34, 35, 36]]]
lista


[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
 [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
 [[25, 26, 27, 28], [29, 30, 31, 32], [33, 34, 35, 36]]]

In [24]:
lista = [[[1, 2, 3],],]
primjer = np.array(lista)
primjer.ndim

3

In [25]:
matrica_nula = np.zeros((5, 3, 3))
matrica_nula

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
matrica_nula.ndim

3

In [31]:
matrica_jedinica = np.ones((5, 3, 3), dtype=np.int16)
matrica_jedinica

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [32]:
matrica_sedmica = 7 * np.ones((5, 3, 3), dtype=np.int16)
matrica_sedmica

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]], dtype=int16)

In [33]:
matrica_sedmica = np.full((5, 3, 3), 7)
matrica_sedmica

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]])

In [34]:
np.arange(5, 15, 3)

array([ 5,  8, 11, 14])

In [35]:
np.linspace(5, 15, 3)

array([ 5., 10., 15.])

In [36]:
np.linspace(5, 15, 5)

array([ 5. ,  7.5, 10. , 12.5, 15. ])

arange i linspace ukupno 4 primjera, i onda za svaki primjer iskoristite reshape u tri razlicita oblika (razlicite dimenzije)

In [38]:
niz = np.linspace(20, 200, 16)
niz

array([ 20.,  32.,  44.,  56.,  68.,  80.,  92., 104., 116., 128., 140.,
       152., 164., 176., 188., 200.])

In [39]:
niz.ndim

1

In [40]:
niz = np.linspace(20, 200, 16).reshape(4,4)
niz

array([[ 20.,  32.,  44.,  56.],
       [ 68.,  80.,  92., 104.],
       [116., 128., 140., 152.],
       [164., 176., 188., 200.]])

In [ ]:
niz[[1], [0]]

array([68.])

In [50]:
niz[[3], [3]]

array([200.])

In [52]:
niz[3,3]

np.float64(200.0)

In [53]:
niz[[2], [2]]

array([140.])

In [54]:
niz[[1, 2, 3], [0, 2, 0]]

array([ 68., 140., 164.])

In [55]:
niz[[1, 2], [0, 2]]

array([ 68., 140.])

In [56]:
niz[1, 2]

np.float64(92.0)

In [48]:
niz[0, 2]

np.float64(44.0)

In [57]:
niz[1::2]

array([[ 68.,  80.,  92., 104.],
       [164., 176., 188., 200.]])

In [58]:
niz[1::2, ::2]

array([[ 68.,  92.],
       [164., 188.]])

In [59]:
niz[1::2][:, ::2]

array([[ 68.,  92.],
       [164., 188.]])

In [60]:
niz_retci = niz[1::2]
niz_retci

array([[ 68.,  80.,  92., 104.],
       [164., 176., 188., 200.]])

In [61]:
niz_retci[:, ::2]

array([[ 68.,  92.],
       [164., 188.]])

In [62]:
niz[0]

array([20., 32., 44., 56.])

In [63]:
niz[0, :]

array([20., 32., 44., 56.])

In [64]:
niz[0, 0:4]

array([20., 32., 44., 56.])

In [65]:
niz[0, np.array([True, True, True, True])]

array([20., 32., 44., 56.])

In [66]:
niz[0, 0:4:1]

array([20., 32., 44., 56.])

In [67]:
list(range(0,4,1))

[0, 1, 2, 3]

In [68]:
list(range(0,4))

[0, 1, 2, 3]

In [69]:
niz[0:2, 2:4]

array([[ 44.,  56.],
       [ 92., 104.]])

In [70]:
niz[0:2:1, 2:4:1]

array([[ 44.,  56.],
       [ 92., 104.]])

In [71]:
niz[0:2, 2:4]

array([[ 44.,  56.],
       [ 92., 104.]])

In [72]:
niz[0:5:2]

array([[ 20.,  32.,  44.,  56.],
       [116., 128., 140., 152.]])

In [73]:
niz[::2]

array([[ 20.,  32.,  44.,  56.],
       [116., 128., 140., 152.]])

In [74]:
niz[:, ::2]

array([[ 20.,  44.],
       [ 68.,  92.],
       [116., 140.],
       [164., 188.]])

In [75]:
niz[:, 1::2]

array([[ 32.,  56.],
       [ 80., 104.],
       [128., 152.],
       [176., 200.]])

In [76]:
niz[-2]

array([116., 128., 140., 152.])

In [77]:
niz[:, -2]

array([ 44.,  92., 140., 188.])

In [78]:
niz[::2, ::2]

array([[ 20.,  44.],
       [116., 140.]])

In [79]:
niz[::2, 1::2]

array([[ 32.,  56.],
       [128., 152.]])

In [80]:
niz[::2, ::-2]

array([[ 56.,  32.],
       [152., 128.]])

In [81]:
niz[:4:2, :2:-2]

array([[ 56.],
       [152.]])

In [82]:
niz[[1], [1]]

array([80.])

In [83]:
niz[[2], [3]]

array([152.])

In [84]:
niz[[1, 2], [1, 3]]

array([ 80., 152.])

In [85]:
niz[[1, 2, 2], [1, 3, 1]]

array([ 80., 152., 128.])

In [86]:
niz

array([[ 20.,  32.,  44.,  56.],
       [ 68.,  80.,  92., 104.],
       [116., 128., 140., 152.],
       [164., 176., 188., 200.]])

In [87]:
novi_niz = niz[1:3, 1:3]
novi_niz

array([[ 80.,  92.],
       [128., 140.]])

In [88]:
novi_niz[:, :] = 777

In [89]:
novi_niz

array([[777., 777.],
       [777., 777.]])

In [90]:
niz

array([[ 20.,  32.,  44.,  56.],
       [ 68., 777., 777., 104.],
       [116., 777., 777., 152.],
       [164., 176., 188., 200.]])

In [91]:
novi_niz_2 = niz[1:3, 1:3].copy()
novi_niz_2

array([[777., 777.],
       [777., 777.]])

In [92]:
novi_niz_2[:, :] = 11

In [93]:
novi_niz_2

array([[11., 11.],
       [11., 11.]])

In [94]:
niz

array([[ 20.,  32.,  44.,  56.],
       [ 68., 777., 777., 104.],
       [116., 777., 777., 152.],
       [164., 176., 188., 200.]])

In [95]:
def funkcija(x, y):
    return 15 * y  + x

matrica_funkcija = np.fromfunction(funkcija, (5, 8), dtype=np.int64 )
matrica_funkcija

array([[  0,  15,  30,  45,  60,  75,  90, 105],
       [  1,  16,  31,  46,  61,  76,  91, 106],
       [  2,  17,  32,  47,  62,  77,  92, 107],
       [  3,  18,  33,  48,  63,  78,  93, 108],
       [  4,  19,  34,  49,  64,  79,  94, 109]])

In [96]:
funkcija = lambda x, y: x*y
tablica_mnozenja = np.fromfunction(funkcija, (13, 13), dtype=np.int64)
tablica_mnozenja

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24],
       [  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36],
       [  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48],
       [  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60],
       [  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72],
       [  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84],
       [  0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96],
       [  0,   9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108],
       [  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [  0,  11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132],
       [  0,  12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144]])

In [97]:
tablica_mnozenja = tablica_mnozenja[1:, 1:]
tablica_mnozenja

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144]])

In [98]:
niz1 = np.array([[1, 2, 3], [4, 5, 6]])
niz1

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
niz2 = np.array([[7,77, 777], [88, 888, 8888]])
niz2

array([[   7,   77,  777],
       [  88,  888, 8888]])

In [100]:
np.concatenate([niz1, niz2])

array([[   1,    2,    3],
       [   4,    5,    6],
       [   7,   77,  777],
       [  88,  888, 8888]])

In [101]:
np.concatenate([niz1, niz2], axis=0)

array([[   1,    2,    3],
       [   4,    5,    6],
       [   7,   77,  777],
       [  88,  888, 8888]])

In [102]:
np.concatenate([niz1, niz2], axis=1)

array([[   1,    2,    3,    7,   77,  777],
       [   4,    5,    6,   88,  888, 8888]])

In [104]:
np.vstack((niz1, niz2))

array([[   1,    2,    3],
       [   4,    5,    6],
       [   7,   77,  777],
       [  88,  888, 8888]])

In [105]:
np.hstack((niz1, niz2))

array([[   1,    2,    3,    7,   77,  777],
       [   4,    5,    6,   88,  888, 8888]])

In [106]:
niz = np.arange(1, 17).reshape(4,4)
niz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [107]:
np.vsplit(niz, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [108]:
np.hsplit(niz, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [109]:
np.hsplit(niz, 4)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [110]:
np.hsplit(niz, np.array([1, 3]))

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [111]:
np.hsplit(niz, np.array([1, 3, 16]))

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]]),
 array([], shape=(4, 0), dtype=int64)]

In [112]:
np.vsplit(niz, np.array([1, 3, 16]))

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]]),
 array([], shape=(0, 4), dtype=int64)]

In [113]:
niz_a = np.arange(1, 65).reshape(8, 8)
niz_b = np.arange(101, 165).reshape(8, 8)

In [114]:
niz_a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [115]:
niz_b


array([[101, 102, 103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114, 115, 116],
       [117, 118, 119, 120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129, 130, 131, 132],
       [133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148],
       [149, 150, 151, 152, 153, 154, 155, 156],
       [157, 158, 159, 160, 161, 162, 163, 164]])

In [116]:
niz_a + niz_b

array([[102, 104, 106, 108, 110, 112, 114, 116],
       [118, 120, 122, 124, 126, 128, 130, 132],
       [134, 136, 138, 140, 142, 144, 146, 148],
       [150, 152, 154, 156, 158, 160, 162, 164],
       [166, 168, 170, 172, 174, 176, 178, 180],
       [182, 184, 186, 188, 190, 192, 194, 196],
       [198, 200, 202, 204, 206, 208, 210, 212],
       [214, 216, 218, 220, 222, 224, 226, 228]])

In [117]:
np.add(niz_a, niz_b)

array([[102, 104, 106, 108, 110, 112, 114, 116],
       [118, 120, 122, 124, 126, 128, 130, 132],
       [134, 136, 138, 140, 142, 144, 146, 148],
       [150, 152, 154, 156, 158, 160, 162, 164],
       [166, 168, 170, 172, 174, 176, 178, 180],
       [182, 184, 186, 188, 190, 192, 194, 196],
       [198, 200, 202, 204, 206, 208, 210, 212],
       [214, 216, 218, 220, 222, 224, 226, 228]])

In [118]:
niz_a - niz_b

array([[-100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100]])

In [119]:
np.mean

<function mean at 0x00000217EC0D75B0>

In [120]:
niz = np.linspace(-4, 4, 9)
niz

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [121]:
np.where(niz < 0, niz * -10, niz**2)

array([40., 30., 20., 10.,  0.,  1.,  4.,  9., 16.])

In [122]:
novi_niz = []
for element in niz:
    if element < 0:
        novi_niz.append(element * -10)
    else:
        novi_niz.append(element **2)
novi_niz

[np.float64(40.0),
 np.float64(30.0),
 np.float64(20.0),
 np.float64(10.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(4.0),
 np.float64(9.0),
 np.float64(16.0)]

In [216]:
np.select([niz < -1, niz < 3, niz>=3], [niz*12, niz**2, niz**3])

array([-48., -36., -24.,   1.,   0.,   1.,   4.,  27.,  64.])

In [123]:
novi_niz = []
for element in niz:
    if element < -1:
        novi_niz.append(element * 12)
    elif element < 3:
        novi_niz.append(element**2)
    elif element>=3:
        novi_niz.append(element**3)
        
novi_niz

[np.float64(-48.0),
 np.float64(-36.0),
 np.float64(-24.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(4.0),
 np.float64(27.0),
 np.float64(64.0)]

In [124]:
np.unique(np.array([4, 6, 7, 4, 4, 5]))

array([4, 5, 6, 7])

In [125]:
set([4, 6, 7, 4, 4, 5])

{4, 5, 6, 7}

In [127]:
niz = np.random.randint(5, size=30)
niz

array([4, 0, 4, 0, 3, 0, 3, 3, 1, 0, 0, 3, 0, 0, 3, 4, 4, 0, 4, 4, 0, 3,
       1, 0, 0, 1, 3, 2, 0, 3], dtype=int32)

In [128]:
np.unique(niz)

array([0, 1, 2, 3, 4], dtype=int32)

In [133]:
niz = np.arange(1, 73).reshape(8, 9)
niz

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71, 72]])

In [134]:
np.fliplr(niz)

array([[ 9,  8,  7,  6,  5,  4,  3,  2,  1],
       [18, 17, 16, 15, 14, 13, 12, 11, 10],
       [27, 26, 25, 24, 23, 22, 21, 20, 19],
       [36, 35, 34, 33, 32, 31, 30, 29, 28],
       [45, 44, 43, 42, 41, 40, 39, 38, 37],
       [54, 53, 52, 51, 50, 49, 48, 47, 46],
       [63, 62, 61, 60, 59, 58, 57, 56, 55],
       [72, 71, 70, 69, 68, 67, 66, 65, 64]])

In [135]:
np.flipud(niz)

array([[64, 65, 66, 67, 68, 69, 70, 71, 72],
       [55, 56, 57, 58, 59, 60, 61, 62, 63],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [138]:
niz = np.random.randint(10, size=16).reshape(4,4)
niz

array([[2, 4, 0, 8],
       [8, 8, 0, 2],
       [1, 8, 4, 0],
       [3, 0, 5, 2]], dtype=int32)

In [139]:
np.sort(niz,axis=0)

array([[1, 0, 0, 0],
       [2, 4, 0, 2],
       [3, 8, 4, 2],
       [8, 8, 5, 8]], dtype=int32)

In [140]:
np.sort(niz,axis=1)

array([[0, 2, 4, 8],
       [0, 2, 8, 8],
       [0, 1, 4, 8],
       [0, 2, 3, 5]], dtype=int32)

In [141]:
niz

array([[2, 4, 0, 8],
       [8, 8, 0, 2],
       [1, 8, 4, 0],
       [3, 0, 5, 2]], dtype=int32)

In [142]:
np.save("test_numpy", niz)

In [143]:
np.savetxt("test_np.txt", niz, header="Tada", footer="afaafa", delimiter=";")


In [144]:
np.savetxt("test_np.txt", niz)

In [145]:
ucitani_niz = np.load("test_numpy.npy")
ucitani_niz

array([[2, 4, 0, 8],
       [8, 8, 0, 2],
       [1, 8, 4, 0],
       [3, 0, 5, 2]], dtype=int32)

In [146]:
ucitani_niz = np.loadtxt("test_np.txt")
ucitani_niz

array([[2., 4., 0., 8.],
       [8., 8., 0., 2.],
       [1., 8., 4., 0.],
       [3., 0., 5., 2.]])

In [147]:
v1 = np.array([1, 8, 3, 5])
v2 = np.array([2, 1, -5, 7])

In [148]:
v1, v2

(array([1, 8, 3, 5]), array([ 2,  1, -5,  7]))

In [149]:
v1.shape

(4,)

In [150]:
v2.shape

(4,)

In [151]:
np.linalg.norm(v1)

np.float64(9.9498743710662)

In [152]:
import math

In [153]:
math.sqrt(1*1 + 8*8 + 3*3 +5*5)

9.9498743710662

In [154]:
np.linalg.norm(v2)

np.float64(8.888194417315589)

In [155]:
v1 + v2

array([ 3,  9, -2, 12])

In [156]:
v1 - v2

array([-1,  7,  8, -2])

In [157]:
5 * v1

array([ 5, 40, 15, 25])

In [158]:
matrica = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrica

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [159]:
type(matrica)

numpy.matrix

In [160]:
type(matrica.base)

numpy.ndarray

In [161]:
A = np.matrix([[1, 2], [3, 4]])
B = np.matrix([[2, 3], [4, 0]])

A, B


(matrix([[1, 2],
         [3, 4]]),
 matrix([[2, 3],
         [4, 0]]))

In [162]:
A+B

matrix([[3, 5],
        [7, 4]])

In [163]:
A-B

matrix([[-1, -1],
        [-1,  4]])

In [164]:
A1 = np.matrix([[1, 2, 3], [3, 4, 5]])
B1 = np.matrix([[2, 3], [4, 0], [7, 8]])

A1, B1

(matrix([[1, 2, 3],
         [3, 4, 5]]),
 matrix([[2, 3],
         [4, 0],
         [7, 8]]))

In [165]:
A1.shape

(2, 3)

In [166]:
B1.shape

(3, 2)

In [167]:
A1 *B1

matrix([[31, 27],
        [57, 49]])

In [168]:
B1 * A1

matrix([[11, 16, 21],
        [ 4,  8, 12],
        [31, 46, 61]])

In [169]:
A2 = np.array([[1, 2], [3, 4]])
B2 = np.array([[2, 3], [4, 0]])

A2, B2

(array([[1, 2],
        [3, 4]]),
 array([[2, 3],
        [4, 0]]))

In [170]:
A2 * B2

array([[ 2,  6],
       [12,  0]])

In [258]:
A2 @ B2

array([[10,  3],
       [22,  9]])

In [171]:
A3 = np.array([[1, 2, 3], [3, 4, 5]])
B3 = np.array([[2, 3], [4, 0], [7, 8]])

A3, B3

(array([[1, 2, 3],
        [3, 4, 5]]),
 array([[2, 3],
        [4, 0],
        [7, 8]]))

In [172]:
A3*B3

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [173]:
A3@B3

array([[31, 27],
       [57, 49]])

In [174]:
B3@A3

array([[11, 16, 21],
       [ 4,  8, 12],
       [31, 46, 61]])

In [175]:
A4 = np.matrix([[1, 2], [3, 4]])
B4 = np.matrix([[2, 3], [4, 0]])

A4, B4

(matrix([[1, 2],
         [3, 4]]),
 matrix([[2, 3],
         [4, 0]]))

In [176]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [181]:
I = np.identity(5)

In [182]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [183]:
1 == 7/7

True

In [186]:
I = A * A^-1

In [187]:
A

matrix([[1, 2],
        [3, 4]])

In [188]:
A^-1

matrix([[-2, -3],
        [-4, -5]])

In [189]:
matrica_2 = np.matrix(10* np.ones((5, 5)))
matrica_2.shape

(5, 5)

In [190]:
I

matrix([[ -8, -11],
        [-16, -23]])

In [191]:
I *matrica_2

ValueError: shapes (2,2) and (5,5) not aligned: 2 (dim 1) != 5 (dim 0)

In [192]:
matrica_2 * I

ValueError: shapes (5,5) and (2,2) not aligned: 5 (dim 1) != 2 (dim 0)

In [193]:
m3 = np.matrix(B3)
m3

matrix([[2, 3],
        [4, 0],
        [7, 8]])

In [194]:
np.transpose(m3)

matrix([[2, 4, 7],
        [3, 0, 8]])

In [195]:
A

matrix([[1, 2],
        [3, 4]])

In [196]:
inv_A = np.linalg.inv(A)
inv_A

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [197]:
inv_A * A

matrix([[ 1.00000000e+00,  4.44089210e-16],
        [-5.55111512e-17,  1.00000000e+00]])

In [198]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [199]:
A * inv_A

matrix([[1.00000000e+00, 1.11022302e-16],
        [0.00000000e+00, 1.00000000e+00]])

In [200]:
A1

matrix([[1, 2, 3],
        [3, 4, 5]])

In [201]:
A2

array([[1, 2],
       [3, 4]])

In [202]:
A3

array([[1, 2, 3],
       [3, 4, 5]])

In [203]:
np.multiply(A1, A1)

matrix([[ 1,  4,  9],
        [ 9, 16, 25]])

In [204]:
A1

matrix([[1, 2, 3],
        [3, 4, 5]])

In [205]:
np.dot(A1, A1)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [206]:
np.dot(A1, B1)

matrix([[31, 27],
        [57, 49]])

In [207]:
import numpy as np

In [208]:
A = np.matrix([[1, 1, 1], [1, 1, 2], [1, 2, 3]])
A

matrix([[1, 1, 1],
        [1, 1, 2],
        [1, 2, 3]])

In [209]:
b = np.matrix([100, 100, 150])
b

matrix([[100, 100, 150]])

In [210]:
b.shape

(1, 3)

In [211]:
b = b.transpose()
b

matrix([[100],
        [100],
        [150]])

In [212]:
x = np.linalg.inv(A) * b
x

matrix([[50.],
        [50.],
        [ 0.]])

In [213]:
x_novo = np.linalg.solve(A, b)
x_novo

matrix([[50.],
        [50.],
        [ 0.]])